version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.05"       # Pequeno consumo para nginx
          memory: "20MB"

  api1: &api
    image: matheuspieropan/rinhabackend2025:3.0
    environment:
      - JAVA_OPTS=-Xms120m -Xmx120m -Djava.net.preferIPv4Stack=true
    hostname: api1
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.45"       # 0.45 CPU para cada api
          memory: "130MB"    # 100MB para cada api

  api2:
    <<: *api
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "130MB"

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
