version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "15MB"
    ports:
      - "9999:9999"
    networks:
      - backend

  api1: &api
    image: matheuspieropan/rinhabackend2025:3.0
    volumes:
      - ./scripts/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
    hostname: api1
    networks:
      - backend
      - payment-processor

  api2:
    <<: *api
    hostname: api2
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
