services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
#  matheuspieropan/rinhabackend2025:graalvm


  api1: &api
    image: gabxdevv/rinha-backend-2025-java:0.0.1-SNAPSHOT
    hostname: api1
    networks:
      - backend
      - payment-processor
    environment:
      TIMEOUT_DEFAULT: 180
      TIMEOUT_FALLBACK: 95
      RETRY_API_DEFAULT: 14
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080/payments
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080/payments
      WORKER_POOL_SIZE: 21

  api2:
    <<: *api
    hostname: api2


  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true