version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend

  api1: &api
    image: matheuspieropan/rinhabackend2025:graalvm
    hostname: api1
    networks:
      - backend
      - payment-processor
    ports:
      - "8080:8080"

  api2:
    <<: *api
    hostname: api2
    ports:
      - "8081:8080"

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true