version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

  api1: &api
    image: matheuspieropan/rinhabackend2025:redis-final
    depends_on:
      redis:
        condition: service_healthy
    hostname: api1
    networks:
      - backend
      - payment-processor
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "90MB"

  api2:
    <<: *api
    hostname: api2
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "90MB"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: [ "redis-server", "--maxmemory", "64mb", "--maxmemory-policy", "allkeys-lru" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "80MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true